version: '2.4'

services:
  localDB:
    image: gauravaher/mysql5-7-with-xmysql:0.1.1
    restart: always
    container_name: MySQL5.7_XMYSQL    
    environment:
      MYSQL_ROOT_PASSWORD: 'root'      
      MYSQL_PASSWORD: 'root'
      MYSQL_DATABASE: 'sandbox'  
      # xmysql variables    
      DATABASE_USER: 'root'
      DATABASE_PASSWORD: 'root'
      DATABASE_NAME: 'gaurav'
    volumes:
      - ./mysql/data/db:/var/lib/mysql      
    ports:
      - "3306:3306"
      - "3000:3000"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10